/* eslint-disable camelcase */

export default {
  urls: [
    // 'https://qa.casino-kit-prod.site/',
    'https://njcasimile.com/',
    // 'https://casino-kit-prod.site/',
    // 'https://casinofiables.com/',
    // 'https://playsafecz.com/',
    // 'https://polskiekasynaonline.net/',
    // 'https://casinotop.at/',
  ],
  endpoints: {
    getParameterForAnticloneTest: '?gbt=wo458yghhy7iw74it66u3t7ewyh8ds6tg',
    invalidEndpoint: 'sdfgh/',
    sitemapEndpoint: 'age=sitemap-custom-polylang',
    adminEndpoint: 'sec-adm/',
    getParamForSelectors: '?automation=blwhp86uwsrv5wtxzlgqpfsecpmnechi',
  },
  secondBlogPage: 'blog/page/2/',
  blogPage: 'blog/',
  webcheckUrl: 'https://web-check.it-boosta.com/',
  webcheckAPI: 'https://web-check.it-boosta.com/web-check-api',
  polylangUrl: 'https://www-data:azimjArnyLy89=@polylangkos.prokit.me/',
  unicodeEditor: 'https://freetools.textmagic.com/unicode-detector',
  attributes: {
    href: 'href',
    hreflang: 'hreflang',
    alt: 'alt',
    title: 'title',
    src: 'src',
    content: 'content',
    srcSet: 'srcset',
    dataPosition: 'data-wcp-ut-position',
    dataID: 'data-wcp-ut-casino-id',
    dataElement: 'data-wcp-ut-convert-element',
    dataLayer: 'data-wcp-ut-data-layer',
    selected: 'selected',
    dataSrcset: 'data-srcset',
    value: 'value',
    checked: 'checked',
    lang: 'lang',
  },
  imageParams: {
    height: 'height',
    width: 'width',
  },
  attributeValues: {
    emptyLink: 'is-empty-link',
  },
  copyrightText: 'Copyright © ',
  crossDomainMenuItems: {
    settings: 'Settings',
    casinos: 'Casinos',
    multilangSettings: 'Multilang Settings',
    categories: 'Categories',
    languages: 'Languages',
  },
  pageTypes: [
    'Casinos',
    'Slots',
    'Payment',
    'Software',
    'Tags/',
    'Post/',
    'Pages',
    'Category',
  ],
  postTypes: ['post', 'page', 'casino', 'slots'],
  taxonomyTypes: ['category', 'payments', 'software'],
  subpages: ['Categories', 'Payments', 'Softwares'],
  plugins: {
    cloakingAnticlone: 'cloaking-anti-clone',
    multilangSettingsHref: 'sitemap-custom-polylang',
  },
  securityData: [
    'search/{search_term_string}/',
    '?author=1',
    '/wp-json/wp/v2/users/',
    '/author/natWEAbl',
  ],
  invalidLogin: 'gghfghFGHJJ',
  invalidPass: '122122121212',
  loginError: 'Error: Invalid Username or Password',
  adminUrlThemeEditor: 'wp-admin/theme-editor.php',
  sitemap: 'sitemap_main.xml',
  promptCredentials: ['admin', 'cegthGfhjkm2022!'], // should be updated in according to creds for web authorization on each project
};
