/* eslint-disable camelcase */

export default {
  endpoints: {
    getParameterForAnticloneTest: '?gbt=wo458yghhy7iw74it66u3t7ewyh8ds6tg',
    invalidEndpoint: 'sdfgh/',
    sitemapEndpoint: 'age=sitemap-custom-polylang',
    adminEndpoint: 'sec-adm/',
    getParamForSelectors: '?automation=blwhp86uwsrv5wtxzlgqpfsecpmnechi',
    paramForCheckingEvents: '?logvisibility=1',
    styleCss: 'wp-content/themes/theme/style.css',
  },
  secondBlogPage: 'blog/page/2/',
  blogPage: 'blog/',
  webcheckAPI: 'https://web-check.it-boosta.com/web-check-api',
  attributes: {
    href: 'href',
    hreflang: 'hreflang',
    alt: 'alt',
    title: 'title',
    src: 'src',
    content: 'content',
    srcSet: 'srcset',
    name: 'data-wcp-ut-casino-name',
    geo: 'data-wcp-ut-geo',
    selected: 'selected',
    dataSrcset: 'data-srcset',
    value: 'value',
    checked: 'checked',
    lang: 'lang',
    style: 'style',
    placeholder: 'placeholder',
  },
  imageParams: {
    height: 'height',
    width: 'width',
  },
  attributeValues: {
    emptyLink: 'is-empty-link',
  },
  copyrightText: 'Copyright © ',
  themeSettingsTabs: {
    singleCasino: 'Single casino',
    general: 'General',
    tableOfContent: 'Table of content',
    quantityOfItems: 'Quantity of items in constructor',
    ctaDataAttrValues: 'CTA data attributes values',
    ctaDataAttrNames: 'CTA data attributes names',
    header: 'Header',
    redirectPage: 'Redirect Page',
    footer: 'Footer',
    casinoIsNotAvailablePopup: 'Casino is not available Pop-up',
    casinos: 'Casinos',
    trackingScript: 'Tracking script',
    providers: 'Providers',
    slotsCategory: 'Slots category',
    iframeOptions: 'Iframe options',
    slotsInfoGroupTitles: 'Slots info group titles',
    micromarkup: 'Micromarkup',
    faq: 'FAQ',
    constructorDefaultSettings: 'Constructor Default settings',
    geoDependentCasinos: 'Geo Depended Casinos',
    gtmScript: 'GTM Script insert',
  },
  pageTypes: [
    'Casinos',
    'Slots',
    'Payment',
    'Software',
    'Tags/',
    'Post/',
    'Pages',
    'Category',
  ],
  postTypes: ['post', 'page', 'casino', 'slots'],
  taxonomyTypes: ['category', 'payments', 'software'],
  subpages: ['Categories', 'Payments', 'Softwares'],
  plugins: {
    cloakingAnticlone: 'cloaking-anti-clone',
    multilangSettingsHref: 'sitemap-custom-polylang',
  },
  securityData: [
    'search/{search_term_string}/',
    '?author=1',
    '/wp-json/wp/v2/users/',
    '/author/natWEAbl',
  ],
  invalidLogin: 'gghfghFGHJJ',
  invalidPass: '122122121212',
  loginError: 'Error: Invalid Username or Password',
  adminUrlThemeEditor: 'wp-admin/theme-editor.php',
  sitemap: 'sitemap_main.xml',
  promptCredentials: ['www-data', 'azimjArnyLy89='], // should be updated in according to creds for web authorization on each project
  loremIpsum: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  textWithH3tag: '<h3>Lorem ipsum dolor sit amet incididunt ut labore et dolore magna aliqua</h3>',
  textWithH4tag: '<h4>Ipsum dolor sit amet incididunt ut labore et dolore magna aliqua</h4>',
  textWithH5tag: '<h5>Dolor sit amet incididunt ut labore et dolore magna aliqua</h5>',
  textWithH6tag: '<h6>Sit amet incididunt ut labore et dolore magna aliqua</h6>',
  randomHeading: 'Random Test Heading 123',
  randomTitle: 'Random test Title 321',
  constructorBlocks: {
    casinos: 'casinos',
    slots: 'slots',
    linking_cards: 'linking-cards',
    payments: 'payments',
    referral: 'referral',
    faq: 'faq',
    author: 'author',
    table_of_content: 'table-of-content',
    tags: 'tags',
    providers: 'providers',
    slots_category: 'slots_category',
    content: 'content',
  }, 
  constructorBlocksData:{
    faq:{
      question: 'question We Have Tested 500+ Online & Offline Casinos Around The World',
      answer: 'We Have Tested 500+ Online & Offline Casinos Around The World'
    }
  }
};
